#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/proddb
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: prod_pass


spring:
  datasource:
    url: jdbc:h2:mem:proddb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info,health
